### ISSUE TITLE
Build failure with GHC 7.8

### ISSUE THREAD

**Issue by andreasabel** [visq/language-c#86]
Latest published version (0.9.0.1) fails to build with GHC 7.8:
```
[32 of 40] Compiling Language.C.Analysis.TravMonad ( src/Language/C/Analysis/TravMonad.hs, dist/build/Language/C/Analysis/TravMonad.o )

src/Language/C/Analysis/TravMonad.hs:432:48:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<*>’ (imported from Control.Applicative)
Error: cabal: Failed to build language-c-0.9.0.1 
```
Building with GHC 7.10 succeeds.

The missing import is probably easily fixable so GHC 7.8 build can be restored.

In my role as hackage trustee, I revised to `base >= 4.8` on hackage to fix the build plan: https://hackage.haskell.org/package/language-c-0.9.0.1/revisions/

**Comment by expipiplus1** [comment]
Wow, that's ancient. Thanks for fixing the build plan!

Not sure it's worth the effort to make a release for this tbh. Please
reopen if it's actually important to you :)

**Comment by andreasabel** [comment]
> reopen if it's actually important to you :)

No, not atm at least.  I was just trying to find out which versions `c2hs` build on (depends on `language-c`).
