### PR TITLE
Fix #86: correct base to >= 4.8 (GHC 7.10)

### LINKED ISSUE #86: Build failure with GHC 7.8
Latest published version (0.9.0.1) fails to build with GHC 7.8:
```
[32 of 40] Compiling Language.C.Analysis.TravMonad ( src/Language/C/Analysis/TravMonad.hs, dist/build/Language/C/Analysis/TravMonad.o )

src/Language/C/Analysis/TravMonad.hs:432:48:
    Not in scope: ‘<$>’
    Perhaps you meant ‘<*>’ (imported from Control.Applicative)
Error: cabal: Failed to build language-c-0.9.0.1 
```
Building with GHC 7.10 succeeds.

The missing import is probably easily fixable so GHC 7.8 build can be restored.

In my role as hackage trustee, I revised to `base >= 4.8` on hackage to fix the build plan: https://hackage.haskell.org/package/language-c-0.9.0.1/revisions/

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #86: correct base to >= 4.8 (GHC 7.10)

7.10 is the least GHC `language-c` builds with.

### CODE REVIEW

**Comment by andreasabel** [comment]
Ping Ellie @expipiplus1

**Comment by expipiplus1** [comment]
Thanks! Sorry that took a while

**Comment by expipiplus1** [comment]
released as https://hackage.haskell.org/package/language-c-0.9.0.2

**Comment by andreasabel** [comment]
> released as [hackage.haskell.org/package/language-c-0.9.0.2](https://hackage.haskell.org/package/language-c-0.9.0.2)

Ah, this wasn't my intention, I only submitted the PR so the bound is correct for future development and releases.
In fact, `language-c-0.9.0.1` already had the correct lower bound after my revision (see https://github.com/visq/language-c/issues/86#issue-1124738037).

Well, no harm done...
